artifacts_root: artifacts



data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/bansi2/Chicken-disease-classification-DL-project/raw/refs/heads/main/Chicken_image.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
